/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuditCalculator: typeof import('./src/components/calculators/AuditCalculator.vue')['default']
    AuditCalculatorPrint: typeof import('./src/components/calculators/AuditCalculatorPrint.vue')['default']
    AuditScore: typeof import('./src/components/AuditScore.vue')['default']
    CalculatorPrintLayout: typeof import('./src/components/calculators/CalculatorPrintLayout.vue')['default']
    CopyDialog: typeof import('./src/components/CopyDialog.vue')['default']
    CustomIcon: typeof import('./src/components/CustomIcon.vue')['default']
    CustomSlider: typeof import('./src/components/CustomSlider.vue')['default']
    DanpssCalculator: typeof import('./src/components/calculators/DanpssCalculator.vue')['default']
    DanpssCalculatorPrint: typeof import('./src/components/calculators/DanpssCalculatorPrint.vue')['default']
    DanpssForm: typeof import('./src/components/DanpssForm.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    EpdsCalculator: typeof import('./src/components/calculators/EpdsCalculator.vue')['default']
    EpdsCalculatorPrint: typeof import('./src/components/calculators/EpdsCalculatorPrint.vue')['default']
    EPDSScore: typeof import('./src/components/EPDSScore.vue')['default']
    EventModal: typeof import('./src/components/calendar/EventModal.vue')['default']
    GcsCalculator: typeof import('./src/components/calculators/GcsCalculator.vue')['default']
    GcsCalculatorPrint: typeof import('./src/components/calculators/GcsCalculatorPrint.vue')['default']
    GCSScore: typeof import('./src/components/GCSScore.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IpssCalculator: typeof import('./src/components/calculators/IpssCalculator.vue')['default']
    IpssCalculatorPrint: typeof import('./src/components/calculators/IpssCalculatorPrint.vue')['default']
    IPSSScore: typeof import('./src/components/IPSSScore.vue')['default']
    LrtiCalculator: typeof import('./src/components/calculators/LrtiCalculator.vue')['default']
    LrtiCalculatorPrint: typeof import('./src/components/calculators/LrtiCalculatorPrint.vue')['default']
    LRTIScore: typeof import('./src/components/LRTIScore.vue')['default']
    MedicalQuestionComponent: typeof import('./src/components/medical/MedicalQuestionComponent.vue')['default']
    MedicalResultsComponent: typeof import('./src/components/medical/MedicalResultsComponent.vue')['default']
    MedicinBoernScore: typeof import('./src/components/MedicinBoernScore.vue')['default']
    NumberSliderInput: typeof import('./src/components/NumberSliderInput.vue')['default']
    PasswordResetComponent: typeof import('./src/components/PasswordResetComponent.vue')['default']
    PersonInfo: typeof import('./src/components/PersonInfo.vue')['default']
    PuqeCalculator: typeof import('./src/components/calculators/PuqeCalculator.vue')['default']
    PuqeCalculatorPrint: typeof import('./src/components/calculators/PuqeCalculatorPrint.vue')['default']
    PUQEScore: typeof import('./src/components/PUQEScore.vue')['default']
    QuestionComponent: typeof import('./src/components/QuestionComponent.vue')['default']
    QuestionSingleComponent: typeof import('./src/components/QuestionSingleComponent.vue')['default']
    RecurrenceForm: typeof import('./src/components/calendar/RecurrenceForm.vue')['default']
    RiskAssessment: typeof import('./src/components/RiskAssessment.vue')['default']
    SurfaceCard: typeof import('./src/components/SurfaceCard.vue')['default']
    SurfaceCardItem: typeof import('./src/components/SurfaceCardItem.vue')['default']
    WestleyCroupCalculator: typeof import('./src/components/calculators/WestleyCroupCalculator.vue')['default']
    WestleyCroupCalculatorPrint: typeof import('./src/components/calculators/WestleyCroupCalculatorPrint.vue')['default']
    WestleyCroupScore: typeof import('./src/components/WestleyCroupScore.vue')['default']
    Who5Calculator: typeof import('./src/components/calculators/Who5Calculator.vue')['default']
    Who5CalculatorPrint: typeof import('./src/components/calculators/Who5CalculatorPrint.vue')['default']
    Who5Score: typeof import('./src/components/Who-5Score.vue')['default']
  }
}
