 
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuditScore: typeof import('./src/components/AuditScore.vue')['default']
    CopyDialog: typeof import('./src/components/CopyDialog.vue')['default']
    CustomIcon: typeof import('./src/components/CustomIcon.vue')['default']
    CustomSlider: typeof import('./src/components/CustomSlider.vue')['default']
    DanpssForm: typeof import('./src/components/DanpssForm.vue')['default']
    EPDSScore: typeof import('./src/components/EPDSScore.vue')['default']
    GCSScore: typeof import('./src/components/GCSScore.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IPSSScore: typeof import('./src/components/IPSSScore.vue')['default']
    LRTIScore: typeof import('./src/components/LRTIScore.vue')['default']
    MedicalQuestionComponent: typeof import('./src/components/medical/MedicalQuestionComponent.vue')['default']
    MedicalResultsComponent: typeof import('./src/components/medical/MedicalResultsComponent.vue')['default']
    MedicinBoernScore: typeof import('./src/components/MedicinBoernScore.vue')['default']
    NumberSliderInput: typeof import('./src/components/NumberSliderInput.vue')['default']
    PasswordResetComponent: typeof import('./src/components/PasswordResetComponent.vue')['default']
    PersonInfo: typeof import('./src/components/PersonInfo.vue')['default']
    PUQEScore: typeof import('./src/components/PUQEScore.vue')['default']
    QuestionComponent: typeof import('./src/components/QuestionComponent.vue')['default']
    QuestionSingleComponent: typeof import('./src/components/QuestionSingleComponent.vue')['default']
    RiskAssessment: typeof import('./src/components/RiskAssessment.vue')['default']
    SurfaceCard: typeof import('./src/components/SurfaceCard.vue')['default']
    SurfaceCardItem: typeof import('./src/components/SurfaceCardItem.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WestleyCroupScore: typeof import('./src/components/WestleyCroupScore.vue')['default']
    Who5Score: typeof import('./src/components/Who-5Score.vue')['default']
  }
}
