name: Claude Code Review
on:
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Only run on PR comments that contain "@claude review"
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '@claude review')
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pullRequest;
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(steps.pr.outputs.result).head.sha }}
          fetch-depth: 0
      
      - name: Add reaction to trigger comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });
      
      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Direct prompt for automated review (no @claude mention needed)
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Focus on the changes in this PR. Be constructive and helpful in your feedback.
            
            PR Author: ${{ fromJson(steps.pr.outputs.result).user.login }}
            PR Title: ${{ fromJson(steps.pr.outputs.result).title }}
            PR Description: ${{ fromJson(steps.pr.outputs.result).body }}
          
          # Optional: Customize review based on PR author experience
          # direct_prompt: |
          #   Review this PR with consideration for the author's experience level:
          #   Author: ${{ fromJson(steps.pr.outputs.result).user.login }}
          #   Association: ${{ fromJson(steps.pr.outputs.result).author_association }}
          #   
          #   ${{ fromJson(steps.pr.outputs.result).author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'This is from a first-time contributor. Be encouraging and provide detailed explanations.' ||
          #   'Provide thorough feedback focusing on our coding standards and best practices.' }}
          #   
          #   Focus on:
          #   - Code quality and best practices
          #   - Potential bugs or security issues
          #   - Performance considerations
          #   - Test coverage and edge cases
          
          # Optional: Add specific tools for running tests or linting
          # allowed_tools: "Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
      
      - name: Add completion reaction
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const reaction = '${{ steps.claude-review.outcome }}' === 'success' ? '+1' : '-1';
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: reaction
            });
